name: schluesselkinder_web

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_APP_NAME: SCHLUESSELKINDER
        NEXT_PUBLIC_WEB_URL: https://schluesselkinder.de
        NEXT_PUBLIC_INTERNAL_CONSOLE_ENABLED: "false"
        NEXT_PUBLIC_SNUFFRAGGA_SPOTIFY_EMBED: "https://open.spotify.com/embed/artist/0Gt1TrN8G1DyXBa2Da5XLW?utm_source=generator"
        NEXT_PUBLIC_SNUFFRAGGA_SOUNDCLOUD_EMBED: "https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/thomas-frerich-681624781%3Futm_source%3Dclipboard%26utm_medium%3Dtext%26utm_campaign%3Dsocial_sharing"
        NEXT_PUBLIC_NEWSLETTER_ENDPOINT: "https://api.schluesselkinder.de/v1/public/newsletter/subscribe"
        NEXT_PUBLIC_SHOP_URL: "https://shop.schluesselkinder.de"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_APP_NAME: SCHLUESSELKINDER
      NEXT_PUBLIC_WEB_URL: https://schluesselkinder.de
      NEXT_PUBLIC_INTERNAL_CONSOLE_ENABLED: "false"
      NEXT_PUBLIC_SNUFFRAGGA_SPOTIFY_EMBED: "https://open.spotify.com/embed/artist/0Gt1TrN8G1DyXBa2Da5XLW?utm_source=generator"
      NEXT_PUBLIC_SNUFFRAGGA_SOUNDCLOUD_EMBED: "https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/thomas-frerich-681624781%3Futm_source%3Dclipboard%26utm_medium%3Dtext%26utm_campaign%3Dsocial_sharing"
      NEXT_PUBLIC_NEWSLETTER_ENDPOINT: "https://api.schluesselkinder.de/v1/public/newsletter/subscribe"
      NEXT_PUBLIC_SHOP_URL: "https://shop.schluesselkinder.de"
    ports:
      - "127.0.0.1:3091:3000"
    restart: unless-stopped
