export { prisma } from "./client.js";
export {
  AssetSourceType,
  AssetType,
  ArtistStatus,
  Channel,
  CompatibilityVerdict,
  ConstraintSource,
  DecisionType,
  EvaluationVerdict,
  FragmentPlacement,
  FragmentType,
  GenerationBriefType,
  GenerationOutputStatus,
  GenerationRequestStatus,
  Prisma,
  PrismaClient,
  PromptSectionType,
  ReleaseStatus,
  ReviewStage,
  ReviewStatus,
  ReviewSubjectType,
  RuleCategory,
  RuleViolationSource,
  RuleSeverity
} from "@prisma/client";
export type {
  ApprovalComment,
  ApprovalDecision,
  Asset,
  AssetTag,
  AssetTagAssignment,
  Artist,
  ArtistCampaignWorld,
  AudiencePersona,
  BrandRule,
  CampaignWorld,
  CampaignWorldAsset,
  CampaignWorldMoodReference,
  CampaignWorldVisualEnvironment,
  ChannelCompositionProfile,
  ChannelFragment,
  ChannelRule,
  ConstraintBundle,
  ForbiddenEnergy,
  Fragment,
  GenerationBrief,
  GenerationBriefConstraint,
  GenerationOutput,
  GenerationOutputEvaluation,
  GenerationRequest,
  LanguageRule,
  MusicRelease,
  MusicReleaseCampaignWorld,
  MoodReference,
  ObjectRelease,
  ReleaseFragment,
  ReviewItem,
  RuleViolation,
  SignalScoringRule,
  Track,
  TrackMoodReference,
  PromptSection,
  VisualRule,
  VisualEnvironment,
  VoiceProfile
} from "@prisma/client";

export const dbReadiness = {
  migrationsEnabled: true,
  prismaSchema: "packages/db/prisma/schema.prisma"
} as const;
