"""S3-compatible Artifact Storage Adapter — S35.

Stores artifact bytes in an S3-compatible bucket (Cloudflare R2, AWS S3,
MinIO, etc.). Metadata is delegated to the ArtifactRegistry (in-memory
or Postgres), same as LocalArtifactStorage.

Hard rules:
- No destructive deletes (no delete_object).
- No list bucket (no list_objects_v2).
- No arbitrary key writes — keys are generated by _safe_storage_key().
- boto3 is imported lazily — local mode never touches it.
- Credentials are never logged, returned in API responses, or exposed in errors.
- If required config is missing, fail loudly at construction time.
"""

from __future__ import annotations

import hashlib
import logging
from datetime import datetime, timezone
from uuid import UUID, uuid4

from app.artifact_registry import ArtifactRegistry
from app.schemas import (
    ArtifactCreateRequest,
    ArtifactDownloadLink,
    ArtifactKind,
    ArtifactRecord,
    ArtifactStatus,
    ArtifactStorageSummary,
)

logger = logging.getLogger(__name__)

# Default presigned URL lifetime: 1 hour
DEFAULT_PRESIGNED_EXPIRY_SECONDS = 3600


def _safe_storage_key(kind: ArtifactKind, artifact_id: UUID, logical_path: str) -> str:
    """Build a deterministic, safe storage key from the artifact metadata.

    Duplicated from artifact_storage.py to avoid circular imports.
    The key is always relative and never contains '..' or absolute path components.
    """
    import os
    import re

    ext = ""
    base = os.path.basename(logical_path)
    if "." in base:
        ext = "." + base.rsplit(".", 1)[-1][:10]
    ext = re.sub(r"[^a-zA-Z0-9.]", "", ext)
    return f"{kind.value}/{artifact_id}{ext}"


class S3ArtifactStorage:
    """S3-compatible artifact storage with pluggable metadata registry.

    Stores binary content in an S3 bucket. Metadata is delegated to an
    ArtifactRegistry (in-memory or Postgres). Storage keys are
    deterministic and safe (no path traversal).

    boto3 is imported lazily at construction time — if it's not installed
    and this class is instantiated, it fails loudly with a clear message.
    """

    def __init__(
        self,
        *,
        endpoint_url: str,
        region: str,
        access_key_id: str,
        secret_access_key: str,
        bucket: str,
        force_path_style: bool = True,
        public_base_url: str | None = None,
        registry: ArtifactRegistry,
    ) -> None:
        # Lazy import of boto3 — fails loudly if not installed
        try:
            import boto3
            from botocore.config import Config as BotoConfig
        except ImportError as exc:
            raise RuntimeError(
                "S3 artifact storage requires the 'boto3' package. "
                "Install via `pip install boto3` or `pip install -e '.[s3]'` "
                "inside the inference service."
            ) from exc

        self._bucket = bucket
        self._public_base_url = public_base_url.rstrip("/") if public_base_url else None
        self._registry = registry

        # Build boto3 client — credentials stay in the client object,
        # never logged or returned in API responses.
        boto_config = BotoConfig(
            s3={"addressing_style": "path" if force_path_style else "virtual"},
            region_name=region,
        )
        self._client = boto3.client(
            "s3",
            endpoint_url=endpoint_url,
            aws_access_key_id=access_key_id,
            aws_secret_access_key=secret_access_key,
            config=boto_config,
        )

        logger.info(
            "S3 artifact storage initialized: endpoint=%s bucket=%s region=%s",
            endpoint_url,
            bucket,
            region,
        )

    @property
    def mode(self) -> str:
        return "s3"

    @property
    def registry(self) -> ArtifactRegistry:
        return self._registry

    @property
    def bucket(self) -> str:
        return self._bucket

    def create_record(
        self,
        request: ArtifactCreateRequest,
        operator_id: str | None = None,
    ) -> ArtifactRecord:
        temp_id = uuid4()
        storage_key = _safe_storage_key(request.kind, temp_id, request.logical_path)
        record = self._registry.create_record(
            request,
            storage_key=storage_key,
            storage_mode="s3",
            operator_id=operator_id,
        )
        # Recompute storage key with real UUID
        real_key = _safe_storage_key(request.kind, record.artifact_id, request.logical_path)
        if real_key != record.storage_key:
            updated = record.model_copy(update={"storage_key": real_key})
            return self._registry.update_record(updated)
        return record

    def store_bytes(
        self,
        artifact_id: UUID,
        data: bytes,
        content_type: str | None = None,
    ) -> ArtifactRecord:
        record = self._registry.get_record(artifact_id)
        if record is None:
            raise ValueError(f"artifact {artifact_id} not found in registry")

        storage_key = record.storage_key
        if storage_key is None:
            raise ValueError(f"artifact {artifact_id} has no storage_key")

        # Validate key safety — no path traversal
        if ".." in storage_key or storage_key.startswith("/"):
            raise ValueError(f"unsafe storage key rejected: {storage_key}")

        # Compute checksum and size before upload
        checksum = hashlib.sha256(data).hexdigest()
        size = len(data)

        # Upload to S3
        ct = content_type or record.content_type
        self._client.put_object(
            Bucket=self._bucket,
            Key=storage_key,
            Body=data,
            ContentType=ct,
            Metadata={
                "artifact-id": str(artifact_id),
                "checksum-sha256": checksum,
            },
        )

        now = datetime.now(timezone.utc)
        updated = record.model_copy(
            update={
                "status": ArtifactStatus.STORED,
                "size_bytes": size,
                "checksum_sha256": checksum,
                "content_type": ct,
                "updated_at": now,
            }
        )
        return self._registry.update_record(updated)

    def get_record(self, artifact_id: UUID) -> ArtifactRecord | None:
        return self._registry.get_record(artifact_id)

    def list_records(self, *, kind: ArtifactKind | None = None) -> list[ArtifactRecord]:
        return self._registry.list_records(kind=kind)

    def get_download_link(self, artifact_id: UUID) -> ArtifactDownloadLink | None:
        record = self._registry.get_record(artifact_id)
        if record is None:
            return None
        if record.status != ArtifactStatus.STORED:
            return None
        if record.storage_key is None:
            return None

        # If public base URL is configured, use direct URL
        if self._public_base_url:
            url = f"{self._public_base_url}/{record.storage_key}"
            return ArtifactDownloadLink(
                artifact_id=artifact_id,
                url=url,
                expires_at=None,
            )

        # Otherwise generate presigned GET URL
        url = self._client.generate_presigned_url(
            "get_object",
            Params={
                "Bucket": self._bucket,
                "Key": record.storage_key,
            },
            ExpiresIn=DEFAULT_PRESIGNED_EXPIRY_SECONDS,
        )
        return ArtifactDownloadLink(
            artifact_id=artifact_id,
            url=url,
            expires_at=None,  # boto3 presigned URLs have internal expiry
        )

    def get_bytes(self, artifact_id: UUID) -> bytes | None:
        """Download artifact bytes from S3.

        Used internally (e.g., for release export ZIP builder).
        Returns None if artifact is not stored or key is missing.
        """
        record = self._registry.get_record(artifact_id)
        if record is None or record.status != ArtifactStatus.STORED:
            return None
        if record.storage_key is None:
            return None

        try:
            response = self._client.get_object(
                Bucket=self._bucket,
                Key=record.storage_key,
            )
            return response["Body"].read()
        except Exception:
            logger.warning(
                "Failed to read artifact %s from S3 key %s",
                artifact_id,
                record.storage_key,
            )
            return None

    def summary(self) -> ArtifactStorageSummary:
        return self._registry.summary(storage_mode=self.mode)
